
export const PATH = {
    home: '/',
    nakazaniq: '/nakazaniq',
    igrachi: '/prava',
    mixzona: '/mix-zona',
    kontakti: '/kontakti',
    pravila: '/pravila',
    hallOfFame: '/hall-of-fame',
    prava: '/prava',
    SelectGolNaMesetsa: '/select-gol-mesets',
    KerelskiIgrachNaSedmitsata: '/kerelski-igrach-sedmitsa',
    GripSocksIgrachNaSedmitsata: '/gripsocks-igrach-sedmitsa',
    VR7ServicesIgrachNaSedmitsata: '/vr7-igrach-sedmitsa',
    BarberShopMartyGolNaSedmitsata: '/barber-gol-sedmitsa',
    CairoFareplay: '/cairo-fareplay',
    IgrataNaArabesk: '/igrata-arabesk',
    superliga: '/superliga',
    malus: '/malus',
    cairo: '/cairo',
    flame: '/flame',
    arabesk: '/arabesk',
    spl4: '/spl4',
    spl5: '/spl5',

}