
export const PATH = {
    home: '/',
    nakazaniq: '/nakazaniq',
    igrachi: '/prava',
    mixzona: '/mix-zona',
    kontakti: '/kontakti',
    pravila: '/pravila',
    hallOfFame: '/hall-of-fame',
    prava: '/prava',
    SelectGolNaMesetsa: '/select-gol-mesets',
    KerelskiIgrachNaSedmitsata: '/kerelski-igrach-sedmitsa',
    GripSocksIgrachNaSedmitsata: '/gripsocks-igrach-sedmitsa',
    VR7ServicesIgrachNaSedmitsata: '/vr7-igrach-sedmitsa',
    BarberShopMartyGolNaSedmitsata: '/barber-gol-sedmitsa',
    CairoFareplay: '/cairo-fareplay',
    IgrataNaArabesk: '/igrata-arabesk',
    superliga: '/superliga',
    malus: '/malus',
    cairo: '/cairo',
    flame: '/flame',
    arabesk: '/arabesk',
    spl4: '/spl4',
    spl5: '/spl5',
    statistikaSuperliga: '/statistika-superliga',
    statistikaMalus: '/statistika-malus',
    statistikaCairo: '/statistika-cairo',
    statistikaFlame: '/statistika-flame',
    statistikaArabesk: '/statistika-arabesk',
    statistikaSpl4: '/statistika-spl4',
    statistikaSpl5: '/statistika-spl5',
    statistikaSever: '/statistika-sever',
    statistikaIztok: '/statistika-iztok',
    statistikaSummer: '/statistika-summer',
    shemaTurnir:'/shema-turnir',
    statistikaKupa: '/statistika-kupa'
}