import './TableStandings.modules.css'

export function TableStandings () {
    return (
        <>
        <div className='standings'>
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Клуб</th>
                        <th>НТ</th>
                        <th>Форма</th>
                        <th>М</th>
                        <th>П</th>
                        <th>Р</th>
                        <th>З</th>
                        <th>Т</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>one</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                        <td>3</td>
                    </tr>
                </tbody>
            </table>
        </div>
        </>
    )
}